### PR TITLE
Change #lang dyn-scope-is-bad to match 2021Fall textbook

### LINKED ISSUE #12: Change smol/dyn-scope-is-bad to match Shriram's 2021 textbook
That is, the only place where the interpreter goes crazy is to fetch environment from the calling side rather than from the place where the closure is constructed.

### PR DESCRIPTION
**Pull request by LuKC1024**
Fix #12

### CODE REVIEW

**Comment by LuKC1024** [comment]
BTW, I spent 2h trying to implement this with `(current-namespace)` and `eval`. Eventually, I realized
- `(current-namespace)` doesn't capture the **current** namespace. Rather, it points to the empty namespace unless you parameterize it.
- Racket's reflection mechanism is fairly restricted (possibly for good reasons). I personally find it difficult to understand and to use.

**Comment by sorawee** [comment]
In Emacs Lisp:

```
(let ((x 1))
  (+ (let ((f (lambda () x)))
       (let ((x 2) (y 3))
         (funcall f)))))
```

evals to `2`. `#lang`'s equivalent program:

```
(let ((x 1))
  (+ (let ((f (lambda () x)))
       (let ((x 2) (y 3))
         (f)))))
```

also evaluates to `2`.

However, in Emacs Lisp:

```
(let ((x 1))
  (+ (let ((f (lambda () x)))
       (let ((x 2) (y 3))
         (funcall f)))
     y))
```

fails with the error unbound id `y`.

With this branch, I think the following program will return 5?

```
(let ((x 1))
  (+ (let ((f (lambda () x)))
       (let ((x 2) (y 3))
         (f)))
     y))
```

**Comment by LuKC1024** [comment]
You are right! Thanks for catching that. The new commit re-implements `let` with left-left-lambda and should fix the problem.

**Comment by LuKC1024** [comment]
Although the error being raised is a syntax error, I think the error is raised at runtime:

```racket
#lang racket
(require "semantics.rkt")

(deffun (f)
  an-unbound-id)

;; You don't see an error unless you uncomment the application.
;(f)
```

Besides, the [documentation of `test/exn`](https://docs.racket-lang.org/plai/plai-scheme.html#%28form._%28%28lib._plai%2Fmain..rkt%29._test%2Fexn%29%29) says that it only catches error raised by [PLAI's `error` function](https://docs.racket-lang.org/plai/plai-scheme.html#%28def._%28%28lib._plai%2Fmain..rkt%29._error%29%29).

**Comment by sorawee** [comment]
Ah, right!

**Comment by LuKC1024** [comment]
Thanks for asking!

**Comment by LuKC1024** [comment]
This PR is now ready to merge. It makes the following changes in addition to what #12 requires:

- add more test cases
- re-implement `let` with `#%app`
- re-implement `deffun` with `defvar`

**Pull request merged**
